### ISSUE TITLE
Will it work on android?

### ISSUE THREAD

**Issue by khan-tm** [jugglingcats/moviemaker#1]

**Comment by jugglingcats** [comment]
The project is Java but intended to run on a server, so the server persists projects, generates the MOV file, etc. It would take quite a bit of work to get all this running on Android IMO.

Am not sure if the Angular web interface itself runs on Android -- never tried it. That is, you would run the server-side somewhere and just point the Android (or iOS why not!) browser at it. It might _just work_.

If you just want an Android app that does stop frame animation, I think there are loads in the app store already.
